config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('final_note.urls'))
]

final_note/urls.py
from django.urls import path
from . import views

app_name="final_note"

urlpatterns = [
    path('',views.index, name='index'),
    path('calcular/',views.calcular_nota, name='calcular')
]

final_note/models.py
from django.db import models

OPCIONES_CLASIFICACION = [
        ('Milagro', 'Milagro'),
        ('Difícil', 'Difícil'),
        ('Aceptable', 'Aceptable'),
        ('Bien', 'Bien'),
        ('Excelente', 'Excelente'),
        ('Perdido', 'Perdido'),
    ]

class Validacion(models.Model):
    

    fecha = models.DateTimeField(auto_now_add=True)
    nota_c1 = models.FloatField()
    nota_c2 = models.FloatField()
    nota_c3 = models.FloatField()
    clasificacion = models.CharField(max_length=10, choices=OPCIONES_CLASIFICACION)

class Mensaje(models.Model):
    texto = models.TextField()
    clasificacion = models.CharField(max_length=10, choices=OPCIONES_CLASIFICACION)

final_note/views.py
from django.shortcuts import render, HttpResponse
from .models import Validacion

def index(request):
    return render(request, 'index.html')


def asignar_clasificacion(nota_c3):
    if nota_c3< 2.0:
        return ('Excelente','Coronao!!','&#128526;')
    elif 2.0 <= nota_c3 and nota_c3< 3.0:
        return ('Bueno','Esta relajado eso','&#128517')
    elif 3.0 <= nota_c3 and nota_c3< 3.8:
        return ('Aceptable','Ponte las pilas','&#128528;')
    elif 3.8 <= nota_c3 and nota_c3< 4.5:
        return ('Difícil','Ponte a rezar','&#128591;')
    elif 4.5 <= nota_c3 and nota_c3<= 5.0:
        return ('Milagro','No vayas a llorar ahora',"&#128534;")
    else:
        return ('Perdido','LLoralo','&#128557;')

def calcular_nota(request):
    if request.method == 'POST':
        n1 = float(request.POST['nota_c1'])
        n2 = float(request.POST['nota_c2'])
        
        # Validación de rango de notas
        if n1 < 0 or n1 > 5 or n2 < 0 or n2 > 5:
            return render(request, 'index.html', {
                "mensaje_error": 'ingresa las notas en el rango que es Njd'
            })
        
        # Cálculo de la nota necesaria para ganar
        else:
            n3 = round((-n1 * 0.3 - n2 * 0.35 + 3.0) / 0.35, 2)
            clasificacion = asignar_clasificacion(n3)
            
            # Creación de una nueva instancia del modelo Validacion
            nueva_validacion = Validacion.objects.create(
                nota_c1=n1,
                nota_c2=n2,
                nota_c3=n3,
                clasificacion=clasificacion[0],
            )
            nueva_validacion.save()
            
            return render(request, 'index.html', {
                "nota_final": n3,
                "mensaje": clasificacion[1],
                "emogi": clasificacion[2]
            })

final_note/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'images/logo_sin_fondo.png' %}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <title>Final Note</title>
  </head>

  <body>    
        <!-- contenedor de secciones  -->
        <div class="col section-container px-0 align-items-center justify-content-center">
        {% block content %}
                {% block page_content %}{% endblock %}
        {% endblock %}
        </div>
    </div>
      
      
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    </body>
</html>

final_note/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block page_content %}

<div class="container col-xl-10 col-xxl-8 px-4 py-5">
  <div class="row align-items-center g-lg-5 py-5">

    <div class="col-lg-7 text-start text-light">
      <!-- respuesta de calculo de nota  -->
      {% if mensaje %}
        <div class="container text-center">
          <div class="row">
            <div class="col-sm-12">
              <h1 class="display-1 fw-bold lh-1 text-light mb-3 rta">{{nota_final}}{{ emogi|safe }}</h1>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
              <h1 class="col-lg-10 fs-1">
                {{mensaje}}
              </h1>
            </div>
          </div>
        </div>
        <!-- mensaje de errorr de rango de notas   -->
        {% elif mensaje_error%}
        <div class="container text-center">
          <div class="row">
            <div class="col-sm-12">
              <h1 class="display-1 fw-bold lh-1 text-light mb-3 rta">&#128545;</h1>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
              <h1 class="col-lg-10 fs-1">
                {{mensaje_error}}
              </h1>
            </div>
          </div>
        </div>
        <!-- salida del index  -->
        {% else %}
        <h1 class="display-4 fw-bold lh-1 text-light mb-3">¿Llevas el semestre arrastrado?</h1>
        <p class="col-lg-10 fs-4">
          Si llevas una materia <span class="text-danger font-weight-bold">perdida</span>&#128531;, ingresa tu nota del primer y segundo corte para ver qué milagro tienes que hacer para ganar en el tercero, y si vas bien, pues bien por ti.&#128077;
        </p>
      {% endif %}
    
    </div>

    <div class="col-md-10 mx-auto col-lg-5">
      <form action="{% url 'final_note:calcular' %}" method="post" class="p-4 p-md-5 rounded-3  form_notas">
        {% csrf_token %}
        <div class="form-floating mb-3">
          <input type="number" name="nota_c1" class="form-control bg-secondary border-0" id="floatingInput" placeholder="2.4" step="0.01" required>
          <label class="text-light">Corte 1</label>
        </div>
        <div class="form-floating mb-3">
          <input type="number" name="nota_c2" class="form-control bg-secondary border-0" id="floatingPassword" placeholder="4.5" step="0.01" required>
          <label class="text-light">Corte 2</label>
        </div>
        <button class="w-100 btn btn-lg btn-success" type="submit">Calcular&#128591;</button>
        <hr class="my-3 border-light">
        <small class="text-light ">Ingrese las notas en el rango valido de 0.0 a 5.0.</small>
      </form>
    </div>
  </div>
</div>
  

{% endblock %}